services:
  gestionnaire-de-site:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=https://supabase-api.swipego.app
    networks:
      - coolify

networks:
  coolify:
    external: true
