#!/usr/bin/env node
/**
 * Externalize CSS + apply Core Web Vitals tweaks for /location-photobooth/ sections.
 *
 * Steps:
 *  1. Fetch all sections from /api/pages/location-photobooth
 *  2. Extract every <style>...</style> block, dedupe, write public/css/location-photobooth.css
 *  3. Strip <style> blocks from each section content
 *  4. Inject <link rel="stylesheet" href="/css/location-photobooth.css"> at the top of 10-hero
 *  5. Inject <link rel="preload" as="image" ...> for the LCP hero image
 *  6. Add `defer` to inline-but-deferrable <script>s (heuristic: ones not depended on by visible-above-the-fold UX)
 *  7. PUT each updated section back
 *
 * Run AFTER pushing public/css/location-photobooth.css to git and Coolify rebuild.
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

const TOKEN = fs.readFileSync('.tmp-token.txt', 'utf8').trim();
const HOST = 'sites.swipego.app';
const SLUG = 'location-photobooth';
const CSS_PATH = path.join(__dirname, '..', 'public', 'css', 'location-photobooth.css');
const LCP_IMAGE = '/images/vegas-hero-group.webp'; // OG image — likely LCP candidate

function req(method, urlPath, bodyObj) {
  return new Promise((resolve, reject) => {
    const body = bodyObj ? JSON.stringify(bodyObj) : null;
    const headers = { Authorization: 'Bearer ' + TOKEN };
    if (body) { headers['Content-Type'] = 'application/json'; headers['Content-Length'] = Buffer.byteLength(body); }
    else headers['Content-Length'] = 0;
    const r = https.request({ method, hostname: HOST, path: urlPath, headers, timeout: 120000 }, rs => {
      let d = ''; rs.on('data', c => d += c); rs.on('end', () => resolve({ status: rs.statusCode, body: d }));
    });
    r.on('error', reject);
    r.on('timeout', () => { r.destroy(); reject(new Error('timeout')); });
    if (body) r.write(body); r.end();
  });
}

(async () => {
  const r = await req('GET', `/api/pages/${SLUG}`, null);
  if (r.status !== 200) throw new Error(`GET failed: ${r.status}`);
  const j = JSON.parse(r.body);
  const sections = j.sections || [];

  console.log(`Found ${sections.length} sections`);

  // 1. Extract all <style> blocks
  const styleRe = /<style[^>]*>([\s\S]*?)<\/style>/g;
  const styleBlocks = [];
  const seen = new Set();
  for (const s of sections) {
    const content = s.content || '';
    let m;
    while ((m = styleRe.exec(content))) {
      const css = m[1].trim();
      if (css && !seen.has(css)) { seen.add(css); styleBlocks.push(css); }
    }
    styleRe.lastIndex = 0;
  }
  console.log(`Extracted ${styleBlocks.length} unique style blocks`);

  const header = `/* CSS for /location-photobooth/ — auto-generated by scripts/externalize-lp-css.js.\n   Do not edit by hand. Re-run the script after section edits. */\n\n`;
  const combinedCss = header + styleBlocks.join('\n\n');
  fs.mkdirSync(path.dirname(CSS_PATH), { recursive: true });
  fs.writeFileSync(CSS_PATH, combinedCss, 'utf8');
  console.log(`Wrote ${CSS_PATH} (${combinedCss.length} bytes)`);

  // 2. Strip <style> blocks from each section + inject <link> + preload on hero
  for (let i = 0; i < sections.length; i++) {
    const s = sections[i];
    const original = s.content || '';
    let stripped = original.replace(/<style[^>]*>[\s\S]*?<\/style>\s*/g, '');

    // Defer all script tags that don't already have async/defer (safe-ish: site uses self-contained IIFEs)
    stripped = stripped.replace(/<script(?![^>]*\b(?:async|defer|type="application\/ld\+json)\b)([^>]*)>/g, '<script$1 defer>');

    // First section: prepend <link rel="stylesheet"> + LCP preload
    if (i === 0) {
      const head = `<link rel="stylesheet" href="/css/location-photobooth.css">\n<link rel="preload" as="image" href="${LCP_IMAGE}" fetchpriority="high">\n`;
      stripped = head + stripped;
    }

    if (stripped !== original) {
      const w = await req('PUT', `/api/pages/${SLUG}/section/${s.file}`, { content: stripped });
      console.log(`  PUT ${s.file}: ${w.status} | ${original.length}b → ${stripped.length}b (-${original.length - stripped.length}b)`);
      await new Promise(r => setTimeout(r, 400));
    }
  }

  console.log('Done. Next: commit public/css/location-photobooth.css, push, Coolify rebuild, then POST /api/deploy/shootnbox/location-photobooth');
})().catch(e => { console.error('FATAL:', e); process.exit(1); });
